# ====================================================================================================
# ====================================================================================================
# ==================================Global Configurations=============================================
# ====================================================================================================
# ====================================================================================================
cloudProvider: minikube

# ====================================================================================================
# Domain app configuration
# ====================================================================================================
domain:
  #enabled, If you set  enabled=true, you should uncomment the following configurations
  enabled: true
  # domainName, Add here your domain or the fixed IP  where the server is running
  domainName: '192.168.49.2'

# ====================================================================================================
# Ingress variables
# ====================================================================================================
ingress:
  enabled: true

# ====================================================================================================
# ====================================================================================================
# ==================================Pods Configurations===============================================
# ====================================================================================================
# ====================================================================================================

# ====================================================================================================
# Variables for microcosm database
# ====================================================================================================
db:
  enabled: true
  #  image:
  #    minikube: 'microcosm-db:v1'
  auth:
    user: postgres
    password: '1234'

# ====================================================================================================
# Variables for microcosm website
# ====================================================================================================
web:
  enabled: true
  # image:
  #   minikube: 'microcosm-openstreetmap-website:v1'
  oauth:
    key: 'aaaaaa'
  service:
    nodePort: 30100

# ====================================================================================================
# Variables for replication-job, Configuration to create the replication files by, minute, hour, or day
# ====================================================================================================
replicationJob:
  enabled: true
  # image:
  #   minikube: 'microcosm-replication-job:v1'

# ====================================================================================================
# Variables for microcosm to pupulate the apidb
# ====================================================================================================
populateApidb:
  enabled: true
  # image:
  #   minikube: 'microcosm-populate-apidb:v1'
  env:
    URL_FILE_TO_IMPORT: 'https://download.geofabrik.de/europe/andorra-latest.osm.pbf'

# ====================================================================================================
# Variables for vector-tiles-db
# ====================================================================================================
vectorTilesDb:
  enabled: true
  # image:
  #   minikube: 'microcosm-vector-tiles-db:v1'
  auth:
    user: postgres
    password: '1234'

# ====================================================================================================
# Variables for imposm
# ====================================================================================================
tilerImposm:
  enabled: true
  # image:
  #   minikube: 'microcosm-imposm:v1'
  env:
    TILER_IMPORT_PBF_URL: https://download.geofabrik.de/europe/andorra-latest.osm.pbf

# ====================================================================================================
# Variables for tegola
# ====================================================================================================
tegola:
  enabled: true
  # image:
  #   minikube: 'microcosm-tiler-server:v1'
  service:
    nodePort: 30101

# ====================================================================================================
# Variables for osm2pgsql
# ====================================================================================================
osm2pgsql:
  enabled: true
  # image:
  #   minikube: microcosm-osm2pgsql:v1

# ====================================================================================================
# Variables for rasterized-tiles-db
# ====================================================================================================
rasterizedTilesDb:
  enabled: true
  # image:
  #   minikube: 'microcosm-tiler-db:v1'
  auth:
    user: postgres
    password: '1234'
# ====================================================================================================
# Variables for mod-tile
# ====================================================================================================
modTile:
  enabled: true
  # image:
  #   minikube: 'microcosm-mod-tile:v1'
  service:
    nodePort: 30102
