settings:
  temp_schema: loading
  schema: public
  data_dir: data
  database: gis
  metadata_table: external_data
sources:
  simplified_water_polygons:
    # The type of file this source is
    type: shp
    # Where to get it
    url: https://osmdata.openstreetmap.de/download/simplified-water-polygons-split-3857.zip
    # The location within the archive
    file: simplified-water-polygons-split-3857/simplified_water_polygons.shp
    archive:
      format: zip
      # Files to extract from the archive
      files:
        - simplified-water-polygons-split-3857/simplified_water_polygons.cpg
        - simplified-water-polygons-split-3857/simplified_water_polygons.dbf
        - simplified-water-polygons-split-3857/simplified_water_polygons.prj
        - simplified-water-polygons-split-3857/simplified_water_polygons.shp
        - simplified-water-polygons-split-3857/simplified_water_polygons.shx
  water_polygons:
    type: shp
    url: https://osmdata.openstreetmap.de/download/water-polygons-split-3857.zip
    file: water-polygons-split-3857/water_polygons.shp
    archive:
      format: zip
      files:
        - water-polygons-split-3857/water_polygons.cpg
        - water-polygons-split-3857/water_polygons.dbf
        - water-polygons-split-3857/water_polygons.prj
        - water-polygons-split-3857/water_polygons.shp
        - water-polygons-split-3857/water_polygons.shx
  icesheet_polygons:
    type: shp
    url: https://osmdata.openstreetmap.de/download/antarctica-icesheet-polygons-3857.zip
    file: antarctica-icesheet-polygons-3857/icesheet_polygons.shp
    archive:
      format: zip
      files:
        - antarctica-icesheet-polygons-3857/icesheet_polygons.cpg
        - antarctica-icesheet-polygons-3857/icesheet_polygons.dbf
        - antarctica-icesheet-polygons-3857/icesheet_polygons.prj
        - antarctica-icesheet-polygons-3857/icesheet_polygons.shp
        - antarctica-icesheet-polygons-3857/icesheet_polygons.shx
  icesheet_outlines:
    type: shp
    url: https://osmdata.openstreetmap.de/download/antarctica-icesheet-outlines-3857.zip
    file: antarctica-icesheet-outlines-3857/icesheet_outlines.shp
    ogropts:
      - '-explodecollections'
    archive:
      format: zip
      files:
        - antarctica-icesheet-outlines-3857/icesheet_outlines.cpg
        - antarctica-icesheet-outlines-3857/icesheet_outlines.dbf
        - antarctica-icesheet-outlines-3857/icesheet_outlines.prj
        - antarctica-icesheet-outlines-3857/icesheet_outlines.shp
        - antarctica-icesheet-outlines-3857/icesheet_outlines.shx
  land_polygons:
    type: shp
    url: https://osmdata.openstreetmap.de/download/land-polygons-split-3857.zip
    file: land-polygons-split-3857/land_polygons.shp
    archive:
      format: zip
      files:
        - land-polygons-split-3857/land_polygons.cpg
        - land-polygons-split-3857/land_polygons.dbf
        - land-polygons-split-3857/land_polygons.prj
        - land-polygons-split-3857/land_polygons.shp
        - land-polygons-split-3857/land_polygons.shx
  ne_110m_admin_0_boundary_lines_land:
    type: shp
    url: https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip
    file: ne_110m_admin_0_boundary_lines_land.shp
    ogropts: &ne_opts
      - '--config'
      - 'SHAPE_ENCODING'
      - 'WINDOWS-1252'
      - '-explodecollections'
      # - '-nlt'
      # - 'PROMOTE_TO_MULTI'
      # needs reprojecting
      - '-t_srs'
      - 'EPSG:3857'
    archive:
      format: zip
      files:
        - ne_110m_admin_0_boundary_lines_land.dbf
        - ne_110m_admin_0_boundary_lines_land.prj
        - ne_110m_admin_0_boundary_lines_land.shp
        - ne_110m_admin_0_boundary_lines_land.shx
  ne_10m_admin_0_boundary_lines_disputed_areas:
    archive:
      files:
        - ne_10m_admin_0_boundary_lines_disputed_areas.cpg
        - ne_10m_admin_0_boundary_lines_disputed_areas.dbf
        - ne_10m_admin_0_boundary_lines_disputed_areas.prj
        - ne_10m_admin_0_boundary_lines_disputed_areas.shp
        - ne_10m_admin_0_boundary_lines_disputed_areas.shx
      format: zip
    file: ne_10m_admin_0_boundary_lines_disputed_areas.shp
    type: shp
    url: https://naciscdn.org/naturalearth/10m/cultural/ne_10m_admin_0_boundary_lines_disputed_areas.zip
    ogropts: *ne_opts
  ne_10m_admin_0_boundary_lines_land:
    archive:
      files:
        - ne_10m_admin_0_boundary_lines_land.cpg
        - ne_10m_admin_0_boundary_lines_land.dbf
        - ne_10m_admin_0_boundary_lines_land.prj
        - ne_10m_admin_0_boundary_lines_land.shp
        - ne_10m_admin_0_boundary_lines_land.shx
      format: zip
    file: ne_10m_admin_0_boundary_lines_land.shp
    type: shp
    url: https://naciscdn.org/naturalearth/10m/cultural/ne_10m_admin_0_boundary_lines_land.zip
    ogropts: *ne_opts
  ne_10m_admin_0_countries:
    archive:
      files:
        - ne_10m_admin_0_countries.cpg
        - ne_10m_admin_0_countries.dbf
        - ne_10m_admin_0_countries.prj
        - ne_10m_admin_0_countries.shp
        - ne_10m_admin_0_countries.shx
      format: zip
    file: ne_10m_admin_0_countries.shp
    type: shp
    url: https://naciscdn.org/naturalearth/10m/cultural/ne_10m_admin_0_countries.zip
    ogropts: *ne_opts
  ne_10m_admin_0_label_points:
    archive:
      files:
        - ne_10m_admin_0_label_points.cpg
        - ne_10m_admin_0_label_points.dbf
        - ne_10m_admin_0_label_points.prj
        - ne_10m_admin_0_label_points.shp
        - ne_10m_admin_0_label_points.shx
      format: zip
    file: ne_10m_admin_0_label_points.shp
    type: shp
    url: https://naciscdn.org/naturalearth/10m/cultural/ne_10m_admin_0_label_points.zip
    ogropts: *ne_opts
  ne_10m_admin_1_label_points:
    archive:
      files:
        - ne_10m_admin_1_label_points.cpg
        - ne_10m_admin_1_label_points.dbf
        - ne_10m_admin_1_label_points.prj
        - ne_10m_admin_1_label_points.shp
        - ne_10m_admin_1_label_points.shx
      format: zip
    file: ne_10m_admin_1_label_points.shp
    type: shp
    url: https://naciscdn.org/naturalearth/10m/cultural/ne_10m_admin_1_label_points.zip
    ogropts: *ne_opts
  ne_10m_admin_1_states_provinces_lines:
    archive:
      files:
        - ne_10m_admin_1_states_provinces_lines.cpg
        - ne_10m_admin_1_states_provinces_lines.dbf
        - ne_10m_admin_1_states_provinces_lines.prj
        - ne_10m_admin_1_states_provinces_lines.shp
        - ne_10m_admin_1_states_provinces_lines.shx
      format: zip
    file: ne_10m_admin_1_states_provinces_lines.shp
    type: shp
    url: https://naciscdn.org/naturalearth/10m/cultural/ne_10m_admin_1_states_provinces_lines.zip
    ogropts: *ne_opts
  ne_10m_land:
    archive:
      files:
        - ne_10m_land.cpg
        - ne_10m_land.dbf
        - ne_10m_land.prj
        - ne_10m_land.shp
        - ne_10m_land.shx
      format: zip
    file: ne_10m_land.shp
    type: shp
    url: https://naciscdn.org/naturalearth/10m/physical/ne_10m_land.zip
    ogropts: *ne_opts
  ne_10m_populated_places:
    archive:
      files:
        - ne_10m_populated_places.cpg
        - ne_10m_populated_places.dbf
        - ne_10m_populated_places.prj
        - ne_10m_populated_places.shp
        - ne_10m_populated_places.shx
      format: zip
    file: ne_10m_populated_places.shp
    type: shp
    url: https://naciscdn.org/naturalearth/10m/cultural/ne_10m_populated_places.zip
    ogropts: *ne_opts
  ne_10m_roads:
    archive:
      files:
        - ne_10m_roads.cpg
        - ne_10m_roads.dbf
        - ne_10m_roads.prj
        - ne_10m_roads.shp
        - ne_10m_roads.shx
      format: zip
    file: ne_10m_roads.shp
    type: shp
    url: https://naciscdn.org/naturalearth/10m/cultural/ne_10m_roads.zip
    ogropts: *ne_opts
  ne_110m_admin_0_countries:
    archive:
      files:
        - ne_110m_admin_0_countries.cpg
        - ne_110m_admin_0_countries.dbf
        - ne_110m_admin_0_countries.prj
        - ne_110m_admin_0_countries.shp
        - ne_110m_admin_0_countries.shx
      format: zip
    file: ne_110m_admin_0_countries.shp
    type: shp
    url: https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_countries.zip
    ogropts: *ne_opts
  ne_110m_admin_1_states_provinces_lines:
    archive:
      files:
        - ne_110m_admin_1_states_provinces_lines.cpg
        - ne_110m_admin_1_states_provinces_lines.dbf
        - ne_110m_admin_1_states_provinces_lines.prj
        - ne_110m_admin_1_states_provinces_lines.shp
        - ne_110m_admin_1_states_provinces_lines.shx
      format: zip
    file: ne_110m_admin_1_states_provinces_lines.shp
    type: shp
    url: https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_1_states_provinces_lines.zip
    ogropts: *ne_opts
  ne_110m_land:
    archive:
      files:
        - ne_110m_land.cpg
        - ne_110m_land.dbf
        - ne_110m_land.prj
        - ne_110m_land.shp
        - ne_110m_land.shx
      format: zip
    file: ne_110m_land.shp
    type: shp
    url: https://naciscdn.org/naturalearth/110m/physical/ne_110m_land.zip
    ogropts: *ne_opts
  ne_110m_populated_places:
    archive:
      files:
        - ne_110m_populated_places.cpg
        - ne_110m_populated_places.dbf
        - ne_110m_populated_places.prj
        - ne_110m_populated_places.shp
        - ne_110m_populated_places.shx
      format: zip
    file: ne_110m_populated_places.shp
    type: shp
    url: https://naciscdn.org/naturalearth/110m/cultural/ne_110m_populated_places.zip
    ogropts: *ne_opts
  ne_50m_admin_0_boundary_lines_disputed_areas:
    archive:
      files:
        - ne_50m_admin_0_boundary_lines_disputed_areas.cpg
        - ne_50m_admin_0_boundary_lines_disputed_areas.dbf
        - ne_50m_admin_0_boundary_lines_disputed_areas.prj
        - ne_50m_admin_0_boundary_lines_disputed_areas.shp
        - ne_50m_admin_0_boundary_lines_disputed_areas.shx
      format: zip
    file: ne_50m_admin_0_boundary_lines_disputed_areas.shp
    type: shp
    url: https://naciscdn.org/naturalearth/50m/cultural/ne_50m_admin_0_boundary_lines_disputed_areas.zip
    ogropts: *ne_opts
  ne_50m_admin_0_boundary_lines_land:
    archive:
      files:
        - ne_50m_admin_0_boundary_lines_land.cpg
        - ne_50m_admin_0_boundary_lines_land.dbf
        - ne_50m_admin_0_boundary_lines_land.prj
        - ne_50m_admin_0_boundary_lines_land.shp
        - ne_50m_admin_0_boundary_lines_land.shx
      format: zip
    file: ne_50m_admin_0_boundary_lines_land.shp
    type: shp
    url: https://naciscdn.org/naturalearth/50m/cultural/ne_50m_admin_0_boundary_lines_land.zip
    ogropts: *ne_opts
  ne_50m_admin_0_countries:
    archive:
      files:
        - ne_50m_admin_0_countries.cpg
        - ne_50m_admin_0_countries.dbf
        - ne_50m_admin_0_countries.prj
        - ne_50m_admin_0_countries.shp
        - ne_50m_admin_0_countries.shx
      format: zip
    file: ne_50m_admin_0_countries.shp
    type: shp
    url: https://naciscdn.org/naturalearth/50m/cultural/ne_50m_admin_0_countries.zip
    ogropts: *ne_opts
  ne_50m_admin_1_states_provinces_lakes:
    archive:
      files:
        - ne_50m_admin_1_states_provinces_lakes.cpg
        - ne_50m_admin_1_states_provinces_lakes.dbf
        - ne_50m_admin_1_states_provinces_lakes.prj
        - ne_50m_admin_1_states_provinces_lakes.shp
        - ne_50m_admin_1_states_provinces_lakes.shx
      format: zip
    file: ne_50m_admin_1_states_provinces_lakes.shp
    type: shp
    url: https://naciscdn.org/naturalearth/50m/cultural/ne_50m_admin_1_states_provinces_lakes.zip
    ogropts: *ne_opts
  ne_50m_admin_1_states_provinces_lines:
    archive:
      files:
        - ne_50m_admin_1_states_provinces_lines.cpg
        - ne_50m_admin_1_states_provinces_lines.dbf
        - ne_50m_admin_1_states_provinces_lines.prj
        - ne_50m_admin_1_states_provinces_lines.shp
        - ne_50m_admin_1_states_provinces_lines.shx
      format: zip
    file: ne_50m_admin_1_states_provinces_lines.shp
    type: shp
    url: https://naciscdn.org/naturalearth/50m/cultural/ne_50m_admin_1_states_provinces_lines.zip
    ogropts: *ne_opts
  ne_50m_land:
    archive:
      files:
        - ne_50m_land.cpg
        - ne_50m_land.dbf
        - ne_50m_land.prj
        - ne_50m_land.shp
        - ne_50m_land.shx
      format: zip
    file: ne_50m_land.shp
    type: shp
    url: https://naciscdn.org/naturalearth/50m/physical/ne_50m_land.zip
    ogropts: *ne_opts
  ne_50m_populated_places:
    archive:
      files:
        - ne_50m_populated_places.cpg
        - ne_50m_populated_places.dbf
        - ne_50m_populated_places.prj
        - ne_50m_populated_places.shp
        - ne_50m_populated_places.shx
      format: zip
    file: ne_50m_populated_places.shp
    type: shp
    url: https://naciscdn.org/naturalearth/50m/cultural/ne_50m_populated_places.zip
    ogropts: *ne_opts
