{{- if .Values.dbbackup.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-db-backup-job
  labels:
    app: {{ template "microcosm.name" . }}
    component: db-backup-job
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  schedule: {{ quote .Values.dbbackup.schedule }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}-db-backup-job
            image: {{ .Values.dbbackup.image }}:{{ .Values.microcosmVersion }}
            command: ['./start.sh']
            {{- if .Values.dbbackup.resources.enabled }}
            resources:
              requests:
                memory: {{ .Values.dbbackup.resources.requests.memory }}
                cpu: {{ .Values.dbbackup.resources.requests.cpu }}
              limits:
                memory: {{ .Values.dbbackup.resources.limits.memory }}
                cpu: {{ .Values.dbbackup.resources.limits.cpu }}
            {{- end }}
            env:
              - name: POSTGRES_HOST
                value: {{ .Release.Name }}-db
              - name: POSTGRES_DB
                value: {{ .Values.webDb.env.POSTGRES_DB }}
              - name: POSTGRES_PASSWORD
                value: {{ quote .Values.webDb.env.POSTGRES_PASSWORD }}
              - name: POSTGRES_USER
                value: {{ .Values.webDb.env.POSTGRES_USER }}
              - name: DB_ACTION
                value: {{ .Values.dbbackup.env.DB_ACTION }}
              - name: RESTORE_URL_FILE
                value: {{.Values.dbbackup.env.RESTORE_URL_FILE}}
              - name: CLEAN_BACKUPS
                value: {{ quote .Values.dbbackup.env.CLEAN_BACKUPS }}
              - name: CLOUDPROVIDER
                value: {{ .Values.cloudProvider }}
              # In case cloudProvider=aws
              {{- if eq .Values.cloudProvider "aws" }}
              - name: AWS_S3_BUCKET
                value: {{ .Values.AWS_S3_BUCKET }}
              {{- end }}
          restartPolicy: OnFailure
{{- end }}
