{{- if .Values.webDb.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web-db-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ template "microcosm.name" . }}
    component: web-db-secret
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
data:
  username:  {{ .Values.webDb.auth.user | b64enc }}
  password: {{ .Values.webDb.auth.password | b64enc }}
{{- end }}
