{{- if .Values.imposm.enabled -}}
{{- if .Values.imposm.persistenceDisk.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-imposm
  labels:
    app: {{ template "microcosm.name" . }}
    component: imposm-statefulset
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app:  {{ .Release.Name }}-imposm
  replicas: 1
  serviceName: {{ .Release.Name }}-imposm
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-imposm
    spec:
      containers:
      - name: {{ .Release.Name }}-imposm
        {{- if eq .Values.cloudProvider "aws" }} 
        image: "{{ .Values.imposm.image.aws }}"
        {{- end }}
        {{- if eq .Values.cloudProvider "minikube" }} 
        image: "{{ .Values.imposm.image.minikube }}"
        {{- end }}
        command: ['./start.sh']
        {{- if .Values.imposm.resources.enabled }}
        resources:
          requests:
            memory: {{ .Values.imposm.resources.requests.memory }}
            cpu: {{ .Values.imposm.resources.requests.cpu }}
          limits:
            memory: {{ .Values.imposm.resources.limits.memory }}
            cpu: {{ .Values.imposm.resources.limits.cpu }}
        {{- end }}
        env:
          - name: IMPOSM_MAPPING_FILE
            value: {{ .Values.imposm.env.MAPPING_FILE }}
          - name: POSTGRES_HOST
            value: {{ .Release.Name }}-vector-tiles-db
          - name: POSTGRES_DB
            value: {{ .Values.vectorTilesDb.env.POSTGRES_DB }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-vector-tiles-db-secret
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-vector-tiles-db-secret
                key: username
          - name: POSTGRES_PORT
            value: {{ .Values.vectorTilesDb.env.POSTGRES_PORT | quote }}
          - name: IMPOSM_IMPORT_FROM
            value: {{ .Values.imposm.env.TILER_IMPORT_FROM }}
          - name: IMPOSM_IMPORT_PBF_URL
            value: {{ .Values.imposm.env.TILER_IMPORT_PBF_URL }}
          # - name: TILER_IMPORT_LIMIT
          #   value: {{ .Values.imposm.env.TILER_IMPORT_LIMIT }}
          - name: CLOUDPROVIDER
            value: {{ .Values.cloudProvider }}
          # In case cloudProvider=aws
          {{- if eq .Values.cloudProvider "aws" }}
          - name: AWS_S3_BUCKET
            value: {{ .Values.AWS_S3_BUCKET }}
          {{- end }}
        volumeMounts:
        - mountPath: {{ .Values.imposm.env.REPLICATION_DIRECTORY }}
          name: replication-storage
        - mountPath: {{ .Values.imposm.persistenceDisk.mountPath }}
          name: imposm-storage
      restartPolicy: Always
      volumes:
        - name: replication-storage
        {{- if .Values.replicationJob.persistenceDisk.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-replication-job-pv-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: imposm-storage
        {{- if .Values.imposm.persistenceDisk.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-imposm-pv-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
{{- end }}
{{- end }}