{{- if .Values.imposm.enabled -}}
## WHY THIS EXISTS? ##
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-imposm
  labels:
    app: {{ template "microcosm.name" . }}
    component: imposm-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: {{ template "microcosm.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-imposm
{{- end }}