{{- if .Values.imposm.enabled -}}
{{- if .Values.imposm.persistenceDisk.data.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-imposm
  labels:
    app: {{ template "microcosm.name" . }}
    component: imposm-statefulset
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app:  {{ .Release.Name }}-imposm
  replicas: 1
  serviceName: {{ .Release.Name }}-imposm
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-imposm
    spec:
      containers:
      - name: {{ .Release.Name }}-imposm
        {{- if eq .Values.cloudProvider "aws" }} 
        image: "{{ .Values.imposm.image.aws }}"
        {{- end }}
        {{- if eq .Values.cloudProvider "minikube" }} 
        image: "{{ .Values.imposm.image.minikube }}"
        {{- end }}
        {{- if .Values.imposm.resources.enabled }}
        resources:
          requests:
            memory: {{ .Values.imposm.resources.requests.memory }}
            cpu: {{ .Values.imposm.resources.requests.cpu }}
          limits:
            memory: {{ .Values.imposm.resources.limits.memory }}
            cpu: {{ .Values.imposm.resources.limits.cpu }}
        {{- end }}
        env:
          - name: POSTGRES_HOST
            value: {{ .Release.Name }}-vector-tiles-db
          - name: POSTGRES_DB
            value: {{ .Values.vectorTilesDb.env.POSTGRES_DB }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-vector-tiles-db-secret
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-vector-tiles-db-secret
                key: username
          - name: POSTGRES_PORT
            value: {{ .Values.vectorTilesDb.env.POSTGRES_PORT | quote }}
          - name: CONFIG_REPLICATION_INTERVAL
            value: {{ .Values.imposm.env.CONFIG_REPLICATION_INTERVAL }}
          - name: IMPOSM_REPLICATION_URL
            value: http://{{ .Release.Name }}-replication-job/
          - name: CONFIG_EXPIRED_TILES_ZOOM
            value: {{ quote .Values.imposm.env.CONFIG_EXPIRED_TILES_ZOOM }}
          - name: CONFIG_EXPIRED_TILES_DIR
            value: {{ .Values.imposm.persistenceDisk.expired.mountPath }}
          # - name: CONFIG_CACHE_DIR
          #   value: {{ .Values.imposm.env.CONFIG_CACHE_DIR }}
          # - name: CONFIG_DIFF_DIR
          #   value: {{ .Values.imposm.env.CONFIG_DIFF_DIR }}
          - name: CLOUDPROVIDER
            value: {{ .Values.cloudProvider }}
          # In case cloudProvider=aws
          {{- if eq .Values.cloudProvider "aws" }}
          - name: AWS_S3_BUCKET
            value: {{ .Values.AWS_S3_BUCKET }}
          {{- end }}
        volumeMounts:
        - mountPath: {{ .Values.imposm.persistenceDisk.data.mountPath }}
          name: imposm-data
        - mountPath: {{ .Values.imposm.persistenceDisk.expired.mountPath }}
          name: imposm-expired
      restartPolicy: Always
      volumes:
        - name: imposm-data
        {{- if .Values.imposm.persistenceDisk.data.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-imposm-data-pv-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: imposm-expired
        {{- if .Values.imposm.persistenceDisk.expired.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-imposm-expired-pv-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
{{- end }}
{{- end }}
