{{- if .Values.modTile.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mod-tile
  labels:
    app: {{ template "microcosm.name" . }}
    component: mod-tile-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  {{- if eq .Values.cloudProvider "aws" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
  {{- end }}
spec:
  # In case cloudProvider=aws
  {{- if eq .Values.cloudProvider "aws" }}
  type: LoadBalancer
  {{- end }}
  

  # In case cloudProvider=minikube
  {{- if eq .Values.cloudProvider "minikube" }}
  type: NodePort
  {{- end }}
  
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      {{- if eq .Values.cloudProvider "minikube" }}
      nodePort: {{ .Values.modTile.service.nodePort }}
      {{- end }}
  selector:
    app: {{ template "microcosm.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-mod-tile
{{- end }}