{{- if .Values.osm2pgsql.enabled -}}
{{- if .Values.osm2pgsql.persistenceDisk.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-osm2pgsql
  labels:
    app: {{ template "microcosm.name" . }}
    component: osm2pgsql
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app:  {{ .Release.Name }}-osm2pgsql
  replicas: 1
  serviceName: {{ .Release.Name }}-osm2pgsql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-osm2pgsql
    spec:
      containers:
      - name: {{ .Release.Name }}-osm2pgsql
        {{- if eq .Values.cloudProvider "aws" }} 
        image: "{{ .Values.osm2pgsql.image.aws }}"
        {{- end }}
        {{- if eq .Values.cloudProvider "minikube" }} 
        image: "{{ .Values.osm2pgsql.image.minikube }}"
        {{- end }}
        command: ['./start.sh']
        {{- if .Values.osm2pgsql.resources.enabled }}
        resources:
          requests:
            memory: {{ .Values.osm2pgsql.resources.requests.memory }}
            cpu: {{ .Values.osm2pgsql.resources.requests.cpu }}
          limits:
            memory: {{ .Values.osm2pgsql.resources.limits.memory }}
            cpu: {{ .Values.osm2pgsql.resources.limits.cpu }}
        {{- end }}
        env:
          - name: POSTGRES_HOST
            value: {{ .Release.Name }}-rasterized-tiles-db
          - name: POSTGRES_DB
            value: {{ .Values.rasterizedTilesDb.env.POSTGRES_DB }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-rasterized-tiles-db-secret
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-rasterized-tiles-db-secret
                key: username
          - name: POSTGRES_PORT
            value: {{ .Values.rasterizedTilesDb.env.POSTGRES_PORT | quote }}
          - name: OSM2PGSQL_UPDATE_INTERVAL
            value: {{ quote .Values.osm2pgsql.env.UPDATE_INTERVAL }}
          - name: REPLICATION_DIR
            value: {{ .Values.osm2pgsql.env.REPLICATION_DIRECTORY }}
          - name: EXPIRED_DIR
            value: {{ .Values.osm2pgsql.env.EXPIRED_DIRECTORY }}
        volumeMounts:
        - mountPath: {{ .Values.osm2pgsql.env.REPLICATION_DIRECTORY }}
          name: replication-storage
        - mountPath: {{ .Values.osm2pgsql.env.EXPIRED_DIRECTORY }}
          name: osm2pgsql-expired-storage
      restartPolicy: Always
      volumes:
        - name: replication-storage
        {{- if .Values.replicationJob.persistenceDisk.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-replication-job-pv-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: osm2pgsql-expired-storage
        {{- if .Values.osm2pgsql.persistenceDisk.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-osm2pgsql-expired-pv-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
{{- end }}
{{- end }}