{{- if .Values.osm2pgsql.enabled -}}
## WHY THIS EXISTS? ##
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-osm2pgsql
  labels:
    app: {{ template "microcosm.name" . }}
    component: osm2pgsql-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: {{ template "microcosm.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-osm2pgsql
{{- end }}