{{- if .Values.planetDump.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-planet-dump-job
  labels:
    app: {{ template "microcosm.name" . }}
    component: planet-dump-job
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  schedule: {{ quote .Values.planetDump.schedule }}
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}-planet-dump-job
            image: {{ .Values.planetDump.image }}:{{ .Values.microcosmVersion }}
            command: ['./start.sh']
            {{- if .Values.planetDump.resources.enabled }}   
            resources:
              requests:
                memory: {{ .Values.planetDump.resources.requests.memory }}
                cpu: {{ .Values.planetDump.resources.requests.cpu }}
              limits:
                memory: {{ .Values.planetDump.resources.limits.memory }}
                cpu: {{ .Values.planetDump.resources.limits.cpu }}
            {{- end }}
            env:
              - name: POSTGRES_HOST
                value: {{ .Release.Name }}-db
              - name: POSTGRES_DB
                value: {{ .Values.webDb.env.POSTGRES_DB }}
              - name: POSTGRES_PASSWORD
                value: {{ quote .Values.webDb.env.POSTGRES_PASSWORD }}
              - name: POSTGRES_USER
                value: {{ .Values.webDb.env.POSTGRES_USER }}
              - name: CLOUDPROVIDER
                value: {{ .Values.cloudProvider }}
              - name: CLEAN_BACKUPS
                value: {{ quote .Values.planetDump.env.CLEAN_BACKUPS }}
              # In case cloudProvider=aws
              {{- if eq .Values.cloudProvider "aws" }}
              - name: AWS_S3_BUCKET
                value: {{ .Values.AWS_S3_BUCKET }}
              {{- end }}
              # Memory optimization for osmosis
              {{- if .Values.planetDump.resources.enabled }}   
              - name: MEMORY_JAVACMD_OPTIONS
                value: {{ .Values.planetDump.resources.requests.memory | default "2Gi" | quote}}
              {{- end }}
          restartPolicy: Never
      backoffLimit: 3
{{- end }}
