{{- if .Values.populateApidb.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-populate-apidb-job
  labels:
    app: {{ template "microcosm.name" . }}
    component: populate-apidb-job
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
    template:
      spec:
        containers:
        - name: {{ .Release.Name }}-populate-apidb-job
          {{- if eq .Values.cloudProvider "aws" }} 
          image: "{{ .Values.populateApidb.image.aws }}"
          {{- end }}
          {{- if eq .Values.cloudProvider "minikube" }} 
          image: "{{ .Values.populateApidb.image.minikube }}"
          {{- end }}
          command: ['./start.sh']
          {{- if .Values.populateApidb.resources.enabled }}   
          resources:
            requests:
              memory: {{ .Values.populateApidb.resources.requests.memory }}
              cpu: {{ .Values.populateApidb.resources.requests.cpu }}
            limits:
              memory: {{ .Values.populateApidb.resources.limits.memory }}
              cpu: {{ .Values.populateApidb.resources.limits.cpu }}
          {{- end }}
          env:
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-web-db
            - name: POSTGRES_DB
              value: {{ .Values.webDb.env.POSTGRES_DB }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-web-db-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-web-db-secret
                  key: username
            - name: URL_FILE_TO_IMPORT
              value: {{.Values.populateApidb.env.URL_FILE_TO_IMPORT}}
            {{- if .Values.populateApidb.resources.enabled }}   
            - name: MEMORY_JAVACMD_OPTIONS
              value: {{ .Values.populateApidb.resources.requests.memory  | default "4Gi" | quote}}
            {{- end }}
        restartPolicy: Never
{{- end }}