{{- if .Values.replicationHttpServer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-replication-http-server
  labels:
    app: {{ template "microcosm.name" . }}
    component: replication-http-server-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- if eq .Values.cloudProvider "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: 80
      targetPort: 80
      # protocol: TCP
      # name: http
  selector:
    app: {{ template "microcosm.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-replication-http-server
{{- end }}