{{- if .Values.tegola.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tegola
  labels:
    app: {{ template "microcosm.name" . }}
    component: tegola-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  {{- if eq .Values.cloudProvider "aws" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
  {{- end }}
spec:
  # In case cloudProvider=aws
  {{- if eq .Values.cloudProvider "aws" }}
  type: LoadBalancer
  {{- end }}

  # In case cloudProvider=minikube
  {{- if eq .Values.cloudProvider "minikube" }}
  type: NodePort
  {{- end }}
  
  ports:
    - port: {{ .Values.tegola.env.TILER_SERVER_PORT }}
      targetPort: {{ .Values.tegola.env.TILER_SERVER_PORT }}
      protocol: TCP
      name: http
      {{- if eq .Values.cloudProvider "minikube" }}
      nodePort: {{ .Values.tegola.service.nodePort }}
      {{- end }}
  selector:
    app: {{ template "microcosm.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-tegola
{{- end }}