{{- if .Values.vectorTilesDb.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vector-tiles-db-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ template "microcosm.name" . }}
    component: vector-tiles-db-secret
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
data:
  username:  {{ .Values.vectorTilesDb.auth.user | b64enc }}
  password: {{ .Values.vectorTilesDb.auth.password | b64enc }}
{{- end }}