{{- if .Values.vectorTilesDb.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-vector-tiles-db
  labels:
    app: {{ template "microcosm.name" . }}
    component: tegola-db-tiler-statefulset
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: 1 # we only ever want one replica of the db
  selector:
    matchLabels:
      app: {{ template "microcosm.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-vector-tiles-db
  serviceName: {{ .Release.Name }}-vector-tiles-db
  template:
    metadata:
      labels:
        app: {{ template "microcosm.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-vector-tiles-db
    spec:
      containers:
        - name: {{ .Chart.Name }}-vector-tiles-db
          {{- if eq .Values.cloudProvider "aws" }} 
          image: "{{ .Values.vectorTilesDb.image.aws }}"
          {{- end }}
          {{- if eq .Values.cloudProvider "minikube" }} 
          image: "{{ .Values.vectorTilesDb.image.minikube }}"
          {{- end }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            # - name: GET_HOSTS_FROM
            #   value: dns
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-vector-tiles-db
            - name: POSTGRES_DB
              value: {{ .Values.vectorTilesDb.env.POSTGRES_DB }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-vector-tiles-db-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-vector-tiles-db-secret
                  key: username
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-vector-tiles-db-secret
                  key: username
            - name: PGDATA
              value: {{ .Values.vectorTilesDb.persistenceDisk.mountPath }}
            - name: POD_IP
              valueFrom: { fieldRef: { fieldPath: status.podIP } }
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready --host $POD_IP
            initialDelaySeconds: 120
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready --host $POD_IP
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
          volumeMounts:
            - name: postgres-storage
              mountPath: {{ .Values.vectorTilesDb.persistenceDisk.mountPath }}
              subPath: {{ .Values.vectorTilesDb.persistenceDisk.subPath }}
          {{- if .Values.vectorTilesDb.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.vectorTilesDb.resources.requests.memory }}
              cpu: {{ .Values.vectorTilesDb.resources.requests.cpu }}
            limits:
              memory: {{ .Values.vectorTilesDb.resources.limits.memory }}
              cpu: {{ .Values.vectorTilesDb.resources.limits.cpu }}
          {{- end }}
      volumes:
        - name: postgres-storage
        {{- if .Values.vectorTilesDb.persistenceDisk.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-vector-tiles-db-pv-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
{{- end }}