{{- if .Values.web.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ template "microcosm.name" . }}
    component: web-secret
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
data:
  oauth_key:  {{ .Values.web.oauth.key | b64enc }}
{{- end }}