{{- if .Values.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app: {{ template "microcosm.name" . }}
    component: web-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "microcosm.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ template "microcosm.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-web
    spec:
      containers:
        - name: {{ .Chart.Name }}-web
          {{- if eq .Values.cloudProvider "aws" }} 
          image: "{{ .Values.web.image.aws }}"
          {{- end }}
          {{- if eq .Values.cloudProvider "minikube" }} 
          image: "{{ .Values.web.image.minikube }}"
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/0.6/capabilities
              port: 80
            initialDelaySeconds: 600 # 10 min, because the compile process takes time.
            timeoutSeconds: 30
          {{- if .Values.web.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.web.resources.requests.memory }}
              cpu: {{ .Values.web.resources.requests.cpu }}
            limits:
              memory: {{ .Values.web.resources.limits.memory }}
              cpu: {{ .Values.web.resources.limits.cpu }}
          {{- end }}
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-web-db # This should give us the host for DB on the cluster.
            - name: POSTGRES_DB
              value: {{ .Values.webDb.env.POSTGRES_DB }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-web-db-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-web-db-secret
                  key: username
            - name: MAILER_ADDRESS
              value: {{ .Values.web.env.MAILER_ADDRESS }}
            - name: MAILER_DOMAIN
              value: {{ .Values.web.env.MAILER_DOMAIN }}
            - name: MAILER_USERNAME
              value: {{ .Values.web.env.MAILER_USERNAME }}
            - name: MAILER_PASSWORD
              value: {{ quote .Values.web.env.MAILER_PASSWORD }}
            # Set domain name or pod ip  
            - name: OAUTH_ID_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-web-secret
                  key: oauth_key
              {{- if .Values.domain.enabled }}
            - name: SERVER_URL
              value: {{ .Values.domain.domainName }}
            - name: SERVER_PROTOCOL
              value : {{ .Values.domain.protocolo }}
              {{- else }}
            - name: SERVER_URL
              value: dns
            - name: SERVER_PROTOCOL
              value : http
              {{- end }}
{{- end }}